"""edits to community

Revision ID: 96d6344dd5ec
Revises: 7387dc23484f
Create Date: 2023-01-24 15:40:11.711458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d6344dd5ec'
down_revision = '7387dc23484f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('description', sa.String(length=2000), nullable=True))
    op.create_unique_constraint(None, 'communities', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'communities', type_='unique')
    op.drop_column('communities', 'description')
    # ### end Alembic commands ###